version: "2.1"

services:
  nextcloud:
    image: nextcloud:23.0.1-apache
    container_name: next_cloud
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=Europe/Netherlands
      # - REDIS_HOST=redis-nextcloud
      # - REDIS_HOST_PASSWORD=YOURREDISPASSWORD
    volumes:
      - ./nextcloud/apps:/var/www/html/apps
      - ./nextcloud/config:/var/www/html/config
      - ./nextcloud/data:/var/www/html/data
      # - ./nextcloud.ini:/usr/local/etc/php/conf.d/nextcloud.ini
    ports:
      - 666:80
    depends_on:
      - postgres
      # - redis-nextcloud

  postgres-nextcloud:
    image: postgres:14.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=postgres_pass
    volumes:
      - ./DB:/var/lib/postgresql/data

  # redis-nextcloud:
  #   image: redis:alpine
  #   container_name: redis-nextcloud
  #   command: redis-server --requirepass YOURREDISPASSWORD
  #   restart: unless-stopped
